spring:
  application:
    name: amount-Service
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
