server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_USERNAME:password}

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  main:
   application:
    name: eureka-server
   allow-bean-definition-overriding: true


