spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  application:
    name: product-service
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: 0